<a href="https://colab.research.google.com/github/MohamedAymanOuchker/pytorch-ML-DL/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [2]:
import torch
print(torch.__version__)

2.0.1+cu118


## Intro to Tensors

### Creating Tensors

Torch tensors - https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 8)
random_tensor

tensor([[[0.7302, 0.6976, 0.0021, 0.0063, 0.0092, 0.9949, 0.1896, 0.7704],
         [0.3332, 0.2221, 0.7778, 0.0624, 0.9634, 0.1160, 0.4005, 0.1161],
         [0.6106, 0.4096, 0.0931, 0.0308, 0.6979, 0.8987, 0.1041, 0.4346],
         [0.2319, 0.6223, 0.3556, 0.0435, 0.7848, 0.6558, 0.8867, 0.2175],
         [0.6551, 0.6557, 0.1132, 0.3792, 0.4787, 0.8583, 0.1333, 0.7784],
         [0.0109, 0.7301, 0.8939, 0.5941, 0.1407, 0.1791, 0.1934, 0.7302],
         [0.5978, 0.4434, 0.1561, 0.2906, 0.0607, 0.5094, 0.0581, 0.7239],
         [0.0139, 0.2081, 0.9337, 0.4093, 0.6237, 0.3966, 0.1093, 0.1236],
         [0.9423, 0.4509, 0.5541, 0.9066, 0.2675, 0.3849, 0.1521, 0.2259],
         [0.5971, 0.5005, 0.5597, 0.0217, 0.4501, 0.1882, 0.0265, 0.0379]]])

In [17]:
random_tensor.ndim

3

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
torch.rand(size=(3, 4))

tensor([[0.4918, 0.3857, 0.0463, 0.3049],
        [0.7563, 0.6542, 0.7285, 0.5796],
        [0.6467, 0.2280, 0.2128, 0.4928]])

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not in the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether the tensor requires gradients
float_32_tensor

tensor([1., 2., 3.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [29]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not in the right device - to get device from a tensor, can use `tensor.device`

In [31]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1229, 0.4756, 0.1030, 0.2746],
        [0.0459, 0.8732, 0.4634, 0.0781],
        [0.5044, 0.2116, 0.2015, 0.6386]])

In [32]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.1229, 0.4756, 0.1030, 0.2746],
        [0.0459, 0.8732, 0.4634, 0.0781],
        [0.5044, 0.2116, 0.2015, 0.6386]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Subtract 10 from a tensor
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Try out PyTorch in-built functions
torch.mul(tensor, 100)

tensor([100, 200, 300])

### Matrix multiplication

Two main ways of performing multuplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplacation needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [37]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [40]:
tensor @ tensor

tensor(14)

In [41]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.33 ms, sys: 66 µs, total: 1.4 ms
Wall time: 3.54 ms


In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 87.5 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [43]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias)

RuntimeError: ignored

In [44]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues, we can manipulate the shape of one of our tensors using **transpose**.
A **transpose** switches the axes or dimensions of a tensor.

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [46]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregations)

In [50]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [55]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [57]:
# Find the positional min and max
x.argmin()

tensor(0)

In [59]:
x.argmax()

tensor(9)