<a href="https://colab.research.google.com/github/MohamedAymanOuchker/pytorch-ML-DL/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


## Intro to Tensors

### Creating Tensors

Torch tensors - https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as Python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 8)
random_tensor

tensor([[[0.5154, 0.7173, 0.8233, 0.8021, 0.4075, 0.2399, 0.9053, 0.6965],
         [0.0169, 0.8680, 0.5427, 0.7954, 0.8756, 0.4751, 0.6897, 0.8457],
         [0.0828, 0.5448, 0.8870, 0.6990, 0.5564, 0.5885, 0.3802, 0.0803],
         [0.9419, 0.9318, 0.3413, 0.3352, 0.7155, 0.2409, 0.8810, 0.0832],
         [0.8863, 0.7924, 0.0374, 0.8932, 0.1561, 0.1796, 0.6588, 0.0840],
         [0.2967, 0.1562, 0.3815, 0.2087, 0.5316, 0.4672, 0.7371, 0.1121],
         [0.7788, 0.9153, 0.9639, 0.7588, 0.3935, 0.2154, 0.5893, 0.6646],
         [0.5977, 0.7477, 0.6743, 0.2120, 0.0029, 0.1089, 0.4373, 0.0621],
         [0.7646, 0.0891, 0.2833, 0.9567, 0.4550, 0.0347, 0.6698, 0.0964],
         [0.8420, 0.5044, 0.8501, 0.7127, 0.4777, 0.2499, 0.3123, 0.4256]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3, 4))

tensor([[0.3097, 0.0727, 0.5835, 0.7772],
        [0.0680, 0.3888, 0.0411, 0.8847],
        [0.7713, 0.7890, 0.1993, 0.9252]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not in the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether the tensor requires gradients
float_32_tensor

tensor([1., 2., 3.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [30]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

## Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not in the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6240, 0.7709, 0.5217, 0.3316],
        [0.8866, 0.0212, 0.2751, 0.8596],
        [0.1485, 0.1376, 0.2321, 0.2753]])

In [33]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.6240, 0.7709, 0.5217, 0.3316],
        [0.8866, 0.0212, 0.2751, 0.8596],
        [0.1485, 0.1376, 0.2321, 0.2753]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


## Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract 10 from a tensor
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 100)

tensor([100, 200, 300])

### Matrix multiplication

Two main ways of performing multuplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplacation needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [38]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
tensor @ tensor

tensor(14)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 353 µs, sys: 0 ns, total: 353 µs
Wall time: 360 µs


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 29 µs, sys: 5 µs, total: 34 µs
Wall time: 47.9 µs


tensor(14)

## One of the most common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias)

RuntimeError: ignored

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues, we can manipulate the shape of one of our tensors using **transpose**.
A **transpose** switches the axes or dimensions of a tensor.

In [47]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [48]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregations)

In [50]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [55]:
# Find the positional min and max
x.argmin()

tensor(0)

In [56]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [57]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [61]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [62]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [63]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [64]:
# torch.permute - rearranges the dimensions of a tarhet tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [65]:
x_original[0, 0, 0] = 72821
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(72821.), tensor(72821.))

## Indexing (selecting data from tensors)
indexing with PyTorch is similar to indexing with NumPy.

In [66]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [69]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [70]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [71]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [72]:
# Get all values of the o dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [73]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy
NumPy is a popular library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [74]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
# Change the tensor, what will this do to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [78]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0978, 0.4596, 0.9585, 0.4063],
        [0.8500, 0.7336, 0.1014, 0.1410],
        [0.3113, 0.9781, 0.0945, 0.4259]])
tensor([[3.5262e-01, 8.9403e-01, 3.9750e-02, 2.7231e-01],
        [2.7641e-01, 8.4777e-01, 1.5621e-01, 6.4415e-04],
        [2.8360e-01, 9.3199e-01, 2.4431e-01, 1.2927e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky-dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investement of purchasing a GPU, there's lot of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [80]:
!nvidia-smi

Sat Sep 30 23:26:07 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------