<a href="https://colab.research.google.com/github/MohamedAymanOuchker/pytorch-ML-DL/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


## Intro to Tensors

### Creating Tensors

Torch tensors - https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as Python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 2, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 10, 8)
random_tensor

tensor([[[0.6217, 0.8732, 0.6750, 0.2289, 0.2283, 0.8733, 0.0804, 0.5655],
         [0.7423, 0.0631, 0.9798, 0.3537, 0.9825, 0.1376, 0.4261, 0.4597],
         [0.7456, 0.5233, 0.0204, 0.6923, 0.5306, 0.6909, 0.9134, 0.5770],
         [0.5498, 0.3116, 0.9465, 0.3201, 0.0611, 0.1685, 0.1111, 0.1252],
         [0.6941, 0.3945, 0.1803, 0.9973, 0.4619, 0.1716, 0.7275, 0.1384],
         [0.1920, 0.3169, 0.0437, 0.0125, 0.0413, 0.2959, 0.9412, 0.3646],
         [0.2027, 0.2186, 0.8459, 0.0360, 0.6787, 0.3977, 0.1706, 0.8452],
         [0.4831, 0.2410, 0.3272, 0.5764, 0.2473, 0.5129, 0.6902, 0.1106],
         [0.0826, 0.6844, 0.1304, 0.1625, 0.1604, 0.0314, 0.4372, 0.4682],
         [0.3721, 0.0060, 0.9385, 0.1284, 0.4669, 0.9324, 0.7228, 0.0493]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
torch.rand(size=(3, 4))

tensor([[0.0401, 0.7863, 0.0612, 0.7920],
        [0.2212, 0.4909, 0.1831, 0.5326],
        [0.5513, 0.4347, 0.0295, 0.3010]])

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [24]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not in the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether the tensor requires gradients
float_32_tensor

tensor([1., 2., 3.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [36]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([1., 4., 9.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not in the right device - to get device from a tensor, can use `tensor.device`

In [38]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3895, 0.2386, 0.7738, 0.7357],
        [0.2191, 0.2946, 0.6841, 0.2837],
        [0.4798, 0.6222, 0.8041, 0.1461]])

In [39]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.3895, 0.2386, 0.7738, 0.7357],
        [0.2191, 0.2946, 0.6841, 0.2837],
        [0.4798, 0.6222, 0.8041, 0.1461]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply a tensor by 10
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subtract 10 from a tensor
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
torch.mul(tensor, 100)

tensor([100, 200, 300])